name: Deploy to server
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Fetch key
        run: |
          echo ${secrets.VPN_FILE} > .github/workflows/client.ovpn
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.VPN_USER }}
          password: ${{ secrets.VPN_PASS }}
      # - name: Set up SSH key
      #   run: |
      #     env
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
      #     sudo apt-get install sshpass

      # - name: Deploy to server
      #   run: |
      #     sshpass -p '${{ secrets.PSWD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} <<'ENDSSH'
          
      #     rm -rf learning_path && mkdir -p learning_path
      #     cd leaning_path
      #     git clone 
      #     docker stop ${{ secrets.APP_NAME }}
      #     docker system prune -f
      #     export ${{ secrets.API_KEY_NAME }}=${{ secrets.API_KEY }}
      #     make deploy_headless
      #     ENDSSH